version: 2

updates:
  # Frontend
  - package-ecosystem: "npm"
    directory: "/frontend"

    schedule:
      interval: "cron"
      cronjob: "50 6 * * *"
      timezone: "Asia/Kolkata"

    open-pull-requests-limit: 5

    versioning-strategy: increase

    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # Backend
  - package-ecosystem: "npm"
    directory: "/backend"

    schedule:
      interval: "cron"
      cronjob: "50 6 * * *"
      timezone: "Asia/Kolkata"

    open-pull-requests-limit: 5

    versioning-strategy: increase

    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"

    schedule:
      interval: "cron"
      cronjob: "50 6 * * *"
      timezone: "Asia/Kolkata"
