apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: gitanalyze-alerts
  namespace: monitoring
  labels:
    release: monitoring

spec:
  groups:
    - name: gitanalyze.rules
      rules:

        - alert: BackendDown
          expr: up{job="backend-service"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Backend Down"
            description: "GitAnalyze-AI backend is unreachable."

        - alert: HighCPUUsage
          expr: rate(process_cpu_seconds_total{job="backend-service"}[5m]) > 0.7
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU Usage"
            description: "CPU usage is above 70%."

        - alert: HighMemoryUsage
          expr: process_resident_memory_bytes{job="backend-service"} > 500000000
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High Memory Usage"
            description: "Memory usage exceeded 500 MB."