prometheus:
  prometheusSpec:
    retention: 15d
    retentionSize: 8GiB

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi